all:
  children:
    proxmox:
      hosts:
        pve1.its.ax:
        pve2.its.ax:
        pve3.its.ax:
    debian_servers:
      hosts:
        wazuh.its.ax:
        webftp.its.ax:
        ansible.its.ax:
        mariadb.its.ax:
