#SPDX-License-Identifier: MIT-0
---
# handlers file for pam_hardening
- name: Rebuild PAM configuration
  ansible.builtin.command:
    cmd: pam-auth-update --force
  environment:
    DEBIAN_FRONTEND: noninteractive
  listen: Rebuild PAM configuration
  changed_when: true
