#SPDX-License-Identifier: MIT-0
---
# vars file for kanidm

# APT repository details
kanidm_ppa_key_url: "https://kanidm.github.io/kanidm_ppa/kanidm_ppa.asc"
kanidm_ppa_key_path: "/etc/apt/trusted.gpg.d/kanidm_ppa.asc"
kanidm_ppa_list_url: "https://kanidm.github.io/kanidm_ppa/kanidm_ppa.list"

# Package name
kanidm_package: kanidm-unixd

# Configuration paths
kanidm_config_dir: /etc/kanidm
kanidm_config_file: "{{ kanidm_config_dir }}/config"
kanidm_unixd_config_file: "{{ kanidm_config_dir }}/unixd"
kanidm_unixd_token_file: "{{ kanidm_config_dir }}/unixd_token"

# Systemd services
kanidm_services:
  - kanidm-unixd
  - kanidm-unixd-tasks
