#SPDX-License-Identifier: MIT-0
---
# handlers file for kernel_hardening
- name: Reload sysctl
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/60-kernel-hardening.conf
  changed_when: true
  become: true
